// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using RaportHelper.Models;
using System;

namespace RaportHelper.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20171204172228_proba z plikami")]
    partial class probazplikami
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RaportHelper.Models.Sessions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Administrator");

                    b.Property<DateTime>("Deadline");

                    b.Property<bool>("Ready");

                    b.Property<string>("SessionName");

                    b.Property<string>("Token");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("RaportHelper.Models.StringData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Data");

                    b.Property<int?>("TasksId");

                    b.HasKey("Id");

                    b.HasIndex("TasksId");

                    b.ToTable("StringData");
                });

            modelBuilder.Entity("RaportHelper.Models.Tasks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<bool>("Ready");

                    b.Property<int>("SessionId");

                    b.HasKey("Id");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("RaportHelper.Models.StringData", b =>
                {
                    b.HasOne("RaportHelper.Models.Tasks")
                        .WithMany("AssignedTo")
                        .HasForeignKey("TasksId");
                });
#pragma warning restore 612, 618
        }
    }
}
